# Conda Environment Setup Instructions
#  - Using an environment.yml file with conda
#  - Key Terminal Commands:

#   TẠO MÔI TRƯỜNG CONDA NẾU CH TẠO
#    conda env create -f environment.yml

#   UPDATE PHIÊN BẢN TRONG FILE ENV CÓ SẴN
#    conda env update --file environment.yml --prune 

#   XEM CÓ NHỮNG PHIÊN BẢN MÔI TRƯỜNG NÀO TRONG MÁY ĐANG CÓ
#    conda env list

#   CHUYỂN SANG ENV CỦA PRJ
#    conda activate environment_name


name: fitness-tracker
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - pandas=2.1.1
  - numpy=1.26.0
  - matplotlib=3.8.0
  - scikit-learn=1.3.0
  - seaborn=0.13.0
  - ipykernel
  - pip
  - pip:
      - jupyter-client==8.4.0
      - jupyter-core==5.4.0